"""
===============================================================================
===============================================================================

This file implements the backend REST API for my Human Action Recognition
system using the FastAPI framework.

The purpose of this API is to allow external clients (web apps, tools,
or testing platforms) to upload a video and receive AI-based predictions
about the human action present in that video.

The system combines:

• CNN (Convolutional Neural Network) for spatial feature extraction
• LSTM (Long Short-Term Memory) for temporal sequence understanding
• Generative AI / LLM for explainable prediction generation

-------------------------------------------------------------------------------
1. WHY I USED FASTAPI
-------------------------------------------------------------------------------

I chose FastAPI instead of Flask for this component because:

• It automatically generates API documentation
• It is faster and asynchronous
• It works well for ML model serving
• It provides automatic request validation

FastAPI is especially useful for deploying AI models as APIs.

-------------------------------------------------------------------------------
2. IMPORTED MODULES
-------------------------------------------------------------------------------

FastAPI related:

FastAPI
    Used to create the main API application.

UploadFile
    Allows uploading files (videos) via API.

File
    Defines the file input type for POST requests.

Python utilities:

shutil
    Used for copying uploaded file data to disk.

os
    Used for file path management and directory creation.

Model script:

run_video
    This function runs the CNN-LSTM model on the uploaded video
    and returns:
        • predicted action
        • confidence score
        • explanation generated by the model.

-------------------------------------------------------------------------------
3. FASTAPI APPLICATION INITIALIZATION
-------------------------------------------------------------------------------

app = FastAPI(...)

This creates the main API server.

Metadata provided:

title
    "Explainable Video Action Recognition with CNN-LSTM and Generative AI"

description
    Explains that the system performs action recognition
    with LLM-based explanations.

version
    Version of the API (currently 1.0).

This metadata automatically appears in FastAPI documentation:

    /docs
    /redoc

-------------------------------------------------------------------------------
4. UPLOAD DIRECTORY
-------------------------------------------------------------------------------

UPLOAD_FOLDER = "static/uploads"

This folder stores uploaded videos before processing.

The following line ensures the directory exists:

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

If the folder does not exist, it will be automatically created.

-------------------------------------------------------------------------------
5. HOME ROUTE
-------------------------------------------------------------------------------

@app.get("/")

This is a simple health-check endpoint.

Purpose:
    Verify that the API server is running correctly.

When accessed, it returns a JSON message:

{
    "message": "Explainable Human Action Recognition with CNN-LSTM and Generative AI is running"
}

This helps during deployment testing.

-------------------------------------------------------------------------------
6. VIDEO PREDICTION API
-------------------------------------------------------------------------------

Endpoint:

    POST /predict-video

This endpoint accepts a video file and performs action recognition.

Input:

file: UploadFile

The user uploads a video file using multipart form data.

-------------------------------------------------------------------------------
7. VIDEO PROCESSING WORKFLOW
-------------------------------------------------------------------------------

Step 1: Save uploaded video

file_path = os.path.join(UPLOAD_FOLDER, file.filename)

The uploaded file is saved in the upload directory.

shutil.copyfileobj() copies the file stream to disk.

-------------------------------------------------------------------------------

Step 2: Run the AI model

action, confidence, explanation = run_video(file_path)

The run_video() function performs:

1) Frame extraction from video
2) Feature extraction using CNN
3) Temporal sequence learning using LSTM
4) Action classification
5) Explanation generation using Generative AI

-------------------------------------------------------------------------------

Step 3: Return prediction result

The API returns a JSON response containing:

{
    "action": predicted action label
    "confidence": probability score of prediction
    "explanation": explanation of why the model predicted this action
}

Example response:

{
    "action": "Punch",
    "confidence": 94.3,
    "explanation": "The model detected repeated forward arm movement
                    with shoulder rotation typical of punching actions."
}

-------------------------------------------------------------------------------
8. SYSTEM ARCHITECTURE ROLE
-------------------------------------------------------------------------------

This API acts as the MODEL SERVING LAYER of the project.

Architecture flow:

User Interface (Flask / HTML)
        ↓
FastAPI Server (api_server.py)
        ↓
CNN-LSTM Model (predict_action.py)
        ↓
Prediction + Explanation
        ↓
JSON Response returned to client

-------------------------------------------------------------------------------
9. WHY THIS API IS IMPORTANT
-------------------------------------------------------------------------------

Creating a separate API layer makes the project:

• Scalable
• Modular
• Easy to integrate with other applications
• Suitable for deployment

For example, this API can be used by:

• Web applications
• Mobile apps
• Research systems
• Real-time monitoring tools

-------------------------------------------------------------------------------
===============================================================================
"""
from fastapi import FastAPI, UploadFile, File
import shutil
import os

from scripts.predict_action import run_video

app = FastAPI(title="Explainable Video Action Recognition with CNN-LSTM and Generative AI")
app = FastAPI(
    title="Explainable Video Action Recognition with CNN-LSTM and Generative AI",
    description="Video action recognition using CNN-LSTM with LLM-based explanation generation.",
    version="1.0"
)
UPLOAD_FOLDER = "static/uploads"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)


@app.get("/")
def home():
    return {"message": "Explainable Human Action Recognition with CNN-LSTM and Generative AI is running"}


@app.post("/predict-video")
async def predict_video(file: UploadFile = File(...)):

    file_path = os.path.join(UPLOAD_FOLDER, file.filename)

    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    action, confidence, explanation = run_video(file_path)

    return {
        "action": action,
        "confidence": confidence,
        "explanation": explanation
    }